### ISSUE TITLE
Please publish new release

### ISSUE THREAD

**Issue by shakefu** [cisagov/pre-commit-packer#11]
No release in almost a year despite active development..  forcing use of `rev: develop` in the pre-commit-config.yml, which generates a warning always.

![image](https://user-images.githubusercontent.com/1046227/140181576-f4f91ae2-4725-491b-bda9-1b17e95570a1.png)

**Comment by mcdonnnj** [comment]
@shakefu I apologize for any confusion on the changes in this project. There has not been a new tag because there have been no changes to the functionality of this hook since the `0.0.2` tag.

We have a system in our organization where projects descend from a parent "skeleton" project. This configuration can be seen in [.github/lineage.yml](https://github.com/cisagov/pre-commit-packer/blob/develop/.github/lineage.yml). We have an [organizational Action](https://github.com/cisagov/action-lineage) that runs periodically to check that repositories with an appropriate configuration have any updates made in this parent skeleton repository pushed down to them. This is how we manage keeping our testing configurations up-to-date among other things.

All of the changes to this project since the `0.0.2` tag have been of this nature. The only changes to the two hooks have been reformatting them because of a change in shell code auto-formatters. You can verify this if you look at the blame for either of the hook files (and the hook configuration). As soon as there are functionality changes we will push a new tag to reflect those changes.

**Comment by shakefu** [comment]
Thanks for the quick response! I'll re-pin my usage. I might suggest that you cut a 1.0.0 release if this code is stable so people don't interpret 0.0.2 as being under heavy development. 👍

**Comment by mcdonnnj** [comment]
> 
> 
> Thanks for the quick response! I'll re-pin my usage. I might suggest that you cut a 1.0.0 release if this code is stable so people don't interpret 0.0.2 as being under heavy development. 👍

Understandable. I'm leaving the door open on a `1.0.0` right now, but you make a fair point.
