### ISSUE TITLE
Latest tag (v0.0.2) is from Dec 2020, what is the recommended way to point to a more recent "version" ?

### ISSUE THREAD

**Issue by marco-m-pix4d** [cisagov/pre-commit-packer#35]
Hello, thanks for pre-commit-packer!

This is not really a bug, but I was unsure where to file it.

I am using this repo in my .pre-commit-config.yaml as

```
- repo: https://github.com/cisagov/pre-commit-packer
  rev: "v0.0.2"
```

I noticed that the latest tag (v0.0.2) is from Dec 2020, while this repo has more recent activity.

Would it be possible to make a more recent tag, or do you have recommendations on how to follow a more recent "version" ?

thanks

**Comment by mcdonnnj** [comment]
@marco-m-pix4d Apologies for the lack of response. The activity since that tag has only been "housekeeping" with updates to our GitHub Actions workflows, the pre-commit configuration, etc., but no updates to the functionality of the hooks. Since I am actually pushing through some updates to this project now you should see a new release in the coming week.

**Comment by marco-m-pix4d** [comment]
Hello @mcdonnnj, thanks!

**Comment by marco-m-pix4d** [comment]
Closing
